import { commitAndPushSpec } from "../workspace-git";
import { openGitHubPr, openAdoPr } from "./git-providers";
import type { HeadlessContext } from "../pipelines/context";

/**
 * Agent: PR Creator (headless)
 *
 * Disk-first flow: writes the generated spec into the local workspace clone,
 * commits + pushes a feature branch off the repository's configured branch
 * (ctx.branch), then opens a PR back into that branch. Routes to GitHub or
 * Azure DevOps based on the repository provider.
 */
export async function runPrCreator(
  ctx: HeadlessContext,
  script: string,
  testType: "e2e" | "exploratory" = "e2e"
): Promise<string> {
  const isExploratory = testType === "exploratory";
  const typeLabel = isExploratory ? "exploratory test" : "e2e test";
  const branchName = `testforge/${testType}-${ctx.taskId.slice(0, 8)}`;
  const fileName = generateFileName(ctx);
  const relFilePath = ctx.outputFolder ? `${ctx.outputFolder}/${fileName}` : fileName;
  const prTitle = `test: add ${typeLabel} — ${ctx.inputText.slice(0, 50)}`;
  const prBody = [
    `## TestForge Auto-Generated ${isExploratory ? "Exploratory" : "E2E"} Test`,
    "",
    `**Application:** ${ctx.applicationName}`,
    `**${isExploratory ? "Target URL" : "Scenario"}:** ${ctx.inputText}`,
    "",
    "This test was automatically generated by TestForge's headless AI agent pipeline.",
  ].join("\n");

  ctx.log("pr_creator", `Creating branch: ${branchName}`);
  ctx.log("pr_creator", `Pushing ${fileName} to ${relFilePath}...`);

  // Disk-first: write -> commit -> push the feature branch off ctx.branch.
  await commitAndPushSpec({
    workspacePath: ctx.workspacePath,
    provider: ctx.repositoryProvider,
    repoUrl: ctx.repositoryUrl,
    pat: ctx.repositoryPat,
    organization: ctx.repositoryOrganization,
    baseBranch: ctx.branch,
    newBranch: branchName,
    relFilePath,
    fileContent: script,
    commitMessage: prTitle,
  });

  let prUrl: string;

  if (ctx.repositoryProvider === "github") {
    const result = await openGitHubPr(
      ctx.repositoryUrl,
      ctx.repositoryPat,
      branchName,
      ctx.branch,
      prTitle,
      prBody
    );
    prUrl = result.prUrl;
  } else if (ctx.repositoryProvider === "ado") {
    if (!ctx.repositoryOrganization) {
      throw new Error("Azure DevOps requires an organization name");
    }
    const result = await openAdoPr(
      ctx.repositoryUrl,
      ctx.repositoryPat,
      ctx.repositoryOrganization,
      branchName,
      ctx.branch,
      prTitle,
      prBody
    );
    prUrl = result.prUrl;
  } else {
    throw new Error(`Unsupported repository provider: ${ctx.repositoryProvider}`);
  }

  ctx.log("pr_creator", "Pull request created successfully.");

  return prUrl;
}

function generateFileName(ctx: HeadlessContext): string {
  const slug = ctx.inputText
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .slice(0, 40)
    .replace(/-$/, "");
  return `${slug}.spec.ts`;
}
