import { createGitHubPr, createAdoPr } from "./git-providers";
import type { HeadlessContext } from "../pipelines/context";

/**
 * Agent: PR Creator (headless)
 *
 * Creates a branch, pushes the test script, and opens a PR. Routes to GitHub or
 * Azure DevOps based on the repository provider. Ported from the source; the
 * scenario id is now `ctx.taskId`, emit is replaced by `ctx.log`, and the test
 * type is simplified to "e2e" | "exploratory".
 */
export async function runPrCreator(
  ctx: HeadlessContext,
  script: string,
  testType: "e2e" | "exploratory" = "e2e"
): Promise<string> {
  const isExploratory = testType === "exploratory";
  const typeLabel = isExploratory ? "exploratory test" : "e2e test";
  const branchName = `testforge/${testType}-${ctx.taskId.slice(0, 8)}`;
  const fileName = generateFileName(ctx);
  const filePath = ctx.outputFolder ? `${ctx.outputFolder}/${fileName}` : fileName;
  const prTitle = `test: add ${typeLabel} — ${ctx.inputText.slice(0, 50)}`;
  const prBody = [
    `## TestForge Auto-Generated ${isExploratory ? "Exploratory" : "E2E"} Test`,
    "",
    `**Application:** ${ctx.applicationName}`,
    `**${isExploratory ? "Target URL" : "Scenario"}:** ${ctx.inputText}`,
    "",
    "This test was automatically generated by TestForge's headless AI agent pipeline.",
  ].join("\n");

  ctx.log("pr_creator", `Creating branch: ${branchName}`);
  ctx.log("pr_creator", `Pushing ${fileName} to ${filePath}...`);

  let prUrl: string;

  if (ctx.repositoryProvider === "github") {
    const result = await createGitHubPr(
      ctx.repositoryUrl,
      ctx.repositoryPat,
      branchName,
      filePath,
      script,
      prTitle,
      prBody
    );
    prUrl = result.prUrl;
  } else if (ctx.repositoryProvider === "ado") {
    if (!ctx.repositoryOrganization) {
      throw new Error("Azure DevOps requires an organization name");
    }
    const result = await createAdoPr(
      ctx.repositoryUrl,
      ctx.repositoryPat,
      ctx.repositoryOrganization,
      branchName,
      filePath,
      script,
      prTitle,
      prBody
    );
    prUrl = result.prUrl;
  } else {
    throw new Error(`Unsupported repository provider: ${ctx.repositoryProvider}`);
  }

  ctx.log("pr_creator", "Pull request created successfully.");

  return prUrl;
}

function generateFileName(ctx: HeadlessContext): string {
  const slug = ctx.inputText
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .slice(0, 40)
    .replace(/-$/, "");
  return `${slug}.spec.ts`;
}
